export const FETCH_MEMBER = 'FETCH_MEMBER';
export const FETCH_POST = 'FETCH_POST';
export const FETCH_COMMENT = 'FETCH_COMMENT';
export const SELECTED_MEMBER = 'SELECTED_MEMBER';
export const SELECTED_POST = 'SELECTED_POST';
export const CREATE_POST = 'CREATE_POST';
export const DELETE_POST = 'DELETE_POST';